apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoriametrics-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoriametrics-config
  namespace: monitoring
data:
  scrape.yaml: |
    global:
      scrape_interval: 60s

    scrape_configs:
      - job_name: victoriametrics
        static_configs:
          - targets: ['localhost:8428']

      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: "true"
            action: keep
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+);(.+)
            replacement: $1:$2
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: victoriametrics
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: victoriametrics
rules:
  - apiGroups: [""]
    resources: [nodes, nodes/proxy, services, endpoints, pods]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get]
  - nonResourceURLs: ["/metrics"]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: victoriametrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: victoriametrics
subjects:
  - kind: ServiceAccount
    name: victoriametrics
    namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoriametrics
  namespace: monitoring
  labels:
    app: victoriametrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      serviceAccountName: victoriametrics
      containers:
        - name: victoriametrics
          image: victoriametrics/victoria-metrics:v1.108.1
          args:
            - -storageDataPath=/data
            - -retentionPeriod=7d
            - -memory.allowedPercent=60
            - -promscrape.config=/config/scrape.yaml
          ports:
            - containerPort: 8428
              name: http
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
          livenessProbe:
            httpGet:
              path: /health
              port: 8428
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8428
            initialDelaySeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: victoriametrics-data
        - name: config
          configMap:
            name: victoriametrics-config
---
apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: monitoring
  labels:
    app: victoriametrics
spec:
  selector:
    app: victoriametrics
  ports:
    - port: 8428
      targetPort: 8428
      name: http
